name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    # NOTE: see this issue for why we don't build on macOS
    # https://github.community/t/api-rate-limit-exceeded-on-actions-setup-go/16237/5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@8d6d5e949675fbadb765c6b1a975047fa5f09b27 #v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run install script
        run: cat install | sh
